### ISSUE TITLE
HMR

### ISSUE THREAD

**Issue by oliviertassinari** [nathanmarks/react-jsstyles-theme-experiment#4]
I'm wondering if [this block](https://github.com/nathanmarks/react-jsstyles-theme-experiment/blob/7b6f3d55a0a3bb549bd83e8b58913e90312009a3/src/styles/styleManager.js#L52) is really needed.
As far as I have looked at the version 3 of `react-hot-loader`. It's re-rendering from the root component.
It will unmount everything.

**Comment by nathanmarks** [comment]
It doesn't remount them, just updates and rerenders
